backend:
  name: git-gateway
  repo: donroops/myPortfolio

media_folder: static/img
public_folder: /img

collections:
  - name: Project
    label: Project
    folder: cms/projects
    create: true
    fields:
      - { name: title, label: Title }
      - { name: summary, label: Summary, widget: 'text' }
      - { name: description, label: Description, widget: 'text' }
      - { name: url, label: URL }
      - {
          name: tech,
          label: Tech List,
          widget: 'list',
          hint: 'Comma seperated list',
        }
      - { label: 'Image', name: 'Image', widget: 'image' }

  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Bio Page'
        name: 'bio'
        file: 'cms/pages/bio.md'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: My bio, name: body, widget: markdown }
